[package]
name = "egor00f/tabslib"

description = "description of package"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = ""

repository = "https://github/"

authors = ["You <you mail>"]

exclude = ["packageName.rbxl"]

private = false

[dependencies]
stdlib = "egor00f/stdlib@0.1.3"
tablelib = "egor00f/tablelib@0.2.0"

[server-dependencies]


[dev-dependencies]

